#!/bin/bash

while read -r line ; do
   if [[ "$line" =~ ^# ]] ; then
      echo >&2 "COMMENT: $line"
   elif [[ "$line" =~ ^([0-9a-fA-F:\.]*)([ \t])([a-zA-Z0-9\.-]*[a-zA-Z0-9-])([\.]|)$ ]] ; then
      if [ "${BASH_REMATCH[3]}" != "nan" ] ; then
         echo "${BASH_REMATCH[1]},${BASH_REMATCH[3]}"
      fi
   else
      echo >&2 "BAD: $line"
   fi
done
